### PR TITLE
Example of mixing net/http and safehttp handlers by nesting muxes.

### PR DESCRIPTION
**Pull request by mikue**

### CODE REVIEW

**Comment by mikue1** [comment]
I wanted to see an example where safehttp and net/http handlers are used in the same server.

Maybe there is a better way to achieve this, let me know :)

**Comment by kele** [comment]
I think this example clearly shows that we need a `ServeMux.Handler(...)` method that returns a safe `net/http.Handler`.

**Comment by kele** [comment]
Take a look: #245.

**Comment by mikue** [comment]
Added another PR #248 for easy comparability.

**Comment by kele** [comment]
Closing in favor of https://github.com/google/go-safeweb/pull/248.

**Pull request closed without merging**
