### PR TITLE
Now we use safehttp.MethodXxxx and safehttp.StatusXxxx everywhere instead of strings and ints

### LINKED ISSUE #121: Cleanup tests to only use safehttp.StatusCode and the request methods provided in mux.go
Currently, some of the frameworks tests don't use `safehttp.StatusCode`s and `safehttp.MethodGet`,  `safehttp.MethodHead`, etc but rather `string`s and `int`s. We should clean up tests for uniformity.

### PR DESCRIPTION
**Pull request by mattiasgrenfeldt**
Fixes #121

### CODE REVIEW

**Review by mihalimara22 — COMMENTED** [review]
What do you think about having the `safehttptest.ResponseRecorder.Status()` also returning a `safehttp.StatusCode` since we are doing the casting in tests anyway.

**Comment by mattiasgrenfeldt** [comment]
That has already been fixed in #106, so we don't need to fix it here.

**Review by mihalimara22 — CHANGES_REQUESTED** [review]
You've forgot the other files in integration tests that contain a `responseRecorder` whose `status` field is an `int`. Please fix them as well in this PR.

**Review by mihalimara22 — APPROVED** [review]

**Comment by kele** [comment]
Sync to master and we can merge. Good job! :)

**Review by kele — APPROVED** [review]

**Comment by mattiasgrenfeldt** [comment]
Done! @kele

**Review by bsiegert — APPROVED** [review]

**Pull request merged**
